### ISSUE TITLE
Windowsで起動するとNoMethodErrorになる

### ISSUE THREAD

**Issue by shimizukawa** [jugyo/termtter#100]
以下にconfig.debug=trueとして出力したトレースバックを添付します。

<pre><code>
[c:\]termtter
[31m[ERROR] NoMethodError: undefined method `text' for #<Hash:0x44125b8>
[0m[31m[ERROR] C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/stdout.rb:98:in `status_line'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/stdout.rb:82:in `print_statuses'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/stdout.rb:81:in `each'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/stdout.rb:81:in `print_statuses'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/stdout.rb:62:in `call'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:170:in `output'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:169:in `each'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:169:in `output'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/standard_commands.rb:22
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/command.rb:62:in `call'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/command.rb:62:in `call'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:217:in `call_commands'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:205:in `each'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:205:in `call_commands'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/task_manager.rb:54:in `invoke_and_wait'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/task_manager.rb:83:in `synchronize'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/task_manager.rb:81:in `synchronize'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/task_manager.rb:53:in `invoke_and_wait'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:194:in `call_commands'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/plugins/defaults/auto_reload.rb:16
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/hook.rb:28:in `call'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/hook.rb:28:in `call'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:188:in `call_hooks'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:186:in `each'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:186:in `call_hooks'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/lib/termtter/client.rb:338:in `run'
C:/Develop/ruby-1.8/lib/ruby/gems/1.8/gems/jugyo-termtter-1.3.1/bin/termtter:6
C:/Develop/ruby-1.8/bin/termtter:19:in `load'
C:/Develop/ruby-1.8/bin/termtter:19
</code></pre>

**Comment by koichiro** [comment]
イイネ！
