### ISSUE TITLE
plug commandでargが無いときにplugin_listがputsされない

### ISSUE THREAD

**Issue by melborne** [jugyo/termtter#120]
plugin commandのexec_procの
      if arg.empty?
        plugin_list
        return
      end
は、
      if arg.empty?
        puts plugin_list.join(', ')
        return
      end
となりますでしょうか。

**Comment by jugyo** [comment]
バグ報告ありがとうございます！
あとで確認して直しておきます！

**Comment by hitode909** [comment]
直しました!!!

**Comment by jugyo** [comment]
Thanks!!!
