### ISSUE TITLE
terminalの背景色が黒だとfollowers commandの表示が見えません

### ISSUE THREAD

**Issue by melborne** [jugyo/termtter#121]
standard_command.rbのfriends_or_followers_commandメソッドの出力色指定が'BLACK'となっています。
     lino.174:    color = user.following ? 'BLACK' : 'RED'
以下のようにしたらどうでしょうか。
      c1, c2 = config.plugins.stdout.colors
      color = user.following ? c2 : c1

**Comment by hitode909** [comment]
直しました．colorsから2色選ぼうとします．
