### ISSUE TITLE
ActiveRubytterのmethod_missingがRubytterのstructizeと挙動が違う

### ISSUE THREAD

**Issue by ohac** [jugyo/termtter#124]
ActiveRubytterの場合、method_missingのとき、キーがなければsuperを呼んで例外になりますが、Rubytterのstructizeで得られたインスタンスではキーがなければnilを返すようになっているように思います。

パッチ案です。
http://gist.github.com/469330

特にtwitterで使っていて現状問題があるわけではないですが、挙動は合わせておいた方がよいのではないでしょうか。

個人的にtwitter APIクローンなサーバを使っていて、in_reply_to_status_id というキーがないときにうまく動かなかった(1.8.0では動いていた)ので変更したいのですが、いかがでしょうか。よければコミットしたいと思いますが。

**Comment by jugyo** [comment]
コミットしてしまって良いと思いますー

**Comment by ohac** [comment]
ありがとうございます。
コミットしておきました。
