### ISSUE TITLE
"Status is over 140 characters" -- how much?

### ISSUE THREAD

**Issue by tremby** [jugyo/termtter#125]
It'd be nice if the "Status is over 140 characters" message was intercepted and the number of characters it was too long by displayed.

**Comment by sorah** [comment]
Now `termtter` can display

> Status is over 140 characters. (+67)

In git/master.

**Comment by tremby** [comment]
Thanks!

**Comment by tremby** [comment]
Actually, I still get
[ERROR] Rubytter::APIError: Status is over 140 characters.

I'm running the latest git.

**Comment by sorah** [comment]
Hmmm.... I pushed again but git shown "Everything up-to-date".

Is your repo is "git://github.com/jugyo/termtter" or "http://github.com/jugyo/termtter.git"?

**Comment by tremby** [comment]
git://github.com/jugyo/termtter.git

Latest commit in it is bba01f90e, which shows the right patch.

I see that the patch acts differently for Ruby >= 1.9 and other -- I am running 1.8.7.
