### ISSUE TITLE
switchが使えなくなった

### ISSUE THREAD

**Issue by authorNari** [jugyo/termtter#129]
こんにちは。

switchが使えなくなっています。

```
switch
```

上記を実行しても、同じアカウントで再度ログインしてしまいます。

コードを覗くとどうやらOAuth対応した際の不具合みたいです。
Termtter::API.setup()でデフォルトのtokenファイルを必ず見てしまうようで、ユーザが変わらないのだと思います。

どのように修正するのがいいのでしょうか。
config.token_fileをユーザ毎に作るというのを思いつきましたが、他に良い案があれば教えて欲しいです。

バグじゃなかったら回避方法を教えてもらえると嬉しいです。

**Comment by Sixeight** [comment]
バグだと思います。ユーザの切り替えが考慮されていなかったために、そもそも OAuth 対応は1アカウント向けになっています。
複数アカウントを使っている人がマイノリティな証拠ですね…。

Termtter会議2010 の時にちょっとだけパッチ書いてたのですが、結局上手くいかず放置しています。
config.token_file の中に複数ユーザのトークンを置くような実装をしていたのですが、複数の token_file を持つ方法でも良さそうです。

(と言いつつ実は回避方法があれば僕も知りたいです。)

**Comment by emasaka** [comment]
バグでしょうねー。というか仕様がこんがらがってる感じだと思います。

ついでにその辺の話に繋げてしまうと、config.token_fileとTermtter::CONF_DIR + config.token_file_nameが重複してるのも気になっていました。

あと、今の実装ではユーザー名をtokenで認証した結果から取ってるので、デフォルトのユーザーをどうするかなと。

というあたりで、叩き台の仕様は、こんな（↓）感じでしょうかねぇ。
- config.token_fileは、プログラム中で設定される、変数っぽい性格のものにする（ユーザーが設定しない）
- デフォルトのconfig.token_fileの値はTermtter::CONF_DIRとconfig.token_fileから生成する
- 最初に認証した結果のデフォルトアカウント名は内部で保持しておく
  - 再度デフォルトユーザーにswitchしたときにデフォルトアカウントを特別扱いするように
- switchしたときに、config.token_fileの値を、Termtter::CONF_DIRとconfig.token_file_nameとアカウント名から生成したものに変更する
  - ただしデフォルトアカウントであればTermtter::CONF_DIRとconfig.token_fileから生成する

そのほかの論点としては、tokenファイルが散らばるのを避けて1つのファイルに複数アカウントぶん入れるかどうか、とか。

**Comment by authorNari** [comment]
コメントありがとうございます。

暇だったのでswitch内で完結するようなパッチを作ってみました。

https://gist.github.com/709419

tokenは複数ファイルになるようにしてます。

ばらけるのがいやな感じかもしれませんが、複数のアカウントといってもせいぜい数個くらいしかないと思われますし、問題ないと考えています。

**Comment by Sixeight** [comment]
cool

ばらける嫌さよりも、削除や修正の容易さが上まわっていると思います。

**Comment by emasaka** [comment]
すごい。コードも仕様もすっきりまとまってますねー。さすが。
私のところでも正常動作しました。
というわけで、pushしちゃっていいんじゃないでしょうか <<< ナニサマ

**Comment by Sixeight** [comment]
authorNari さんの変更を取りこみました。

**Comment by jugyo** [comment]
反応が遅くなって済みません。
良いと思いますー
