### ISSUE TITLE
-uオプションを削除するのはどうでしょう

### ISSUE THREAD

**Issue by emasaka** [jugyo/termtter#131]
oAuth化してから -u (--user) オプションが意味なくなってますよね。

まぎらわしいので削除するのはどうでしょうか。

とりあえずremove_u_optionブランチをpushしました。

**Comment by jugyo** [comment]
消しちゃってください！

**Comment by emasaka** [comment]
らじゃ！ mergeしてpushしました。

**Comment by jugyo** [comment]
あざっす！
