### ISSUE TITLE
get status until last time

### ISSUE THREAD

**Issue by gogonkt** [jugyo/termtter#132]
advice:
twitter api doc:
 /home_timeline.json?since_id=12345
 can get timeline until last time(until status_id). 
Is it nessesary?

**Comment by jugyo** [comment]
Termtter uses the since_id when fetch new timeline.

**Comment by gogonkt** [comment]
oh, why not fetch all new timeline since last logout when termtter start
for example: there are 120 tweets since logout, 
but termtter only fetch 30. ?_?

**Comment by gogonkt** [comment]
Termtter 1.9.0, gem install

**Comment by jugyo** [comment]
> oh, why not fetch all new timeline since last logout when termtter start

make sence.
frequently, I use the list command with '-' option:

```
> list -100
```

How do you like it?

**Comment by gogonkt** [comment]
I do use '-' too,
auto get new timeline when start make sence for me.
regar
-- gogonkt
