### ISSUE TITLE
howto use proxy?

### ISSUE THREAD

**Issue by gogonkt** [jugyo/termtter#133]
http_proxy='127.0.0.1:8118'  termtter
but failt
and set
  config.proxy.host = '127.0.0.1'
  config.proxy.port = '8118'
both not work,

<<% http_proxy='127.0.0.1:8118'  termtter 2>&1 |wgetpaste>>
output: http://paste.pocoo.org/show/322035/

Termtter 1.9.0
install from Gem
8118 is privoxy http proxy

**Comment by emasaka** [comment]
What if  <<HTTP_PROXY='127.0.0.1:8118' termtter>>  ?

(trunk version recognizes http_proxy (in downcase), but released version does not.)

**Comment by gogonkt** [comment]
<<http_proxy='http://127.0.0.1:8118'  termtter>> worked final, :D
it need 'http://' 囧， so intresting
Termtter 1.9.0 http_proxy worked , upper case don't
