### ISSUE TITLE
goo.gl urlshorter

### ISSUE THREAD

**Issue by itwars** [jugyo/termtter#137]
I'm not used with GitHub
I've rewritten a plugin to manage goo.gl url shorter ... Here is the code :
# -_\- coding: utf-8 -_-
# 

require 'googl'

Termtter::Client.register_hook(
    :name   =>  :googlURL, 
    :points =>  [:modify_arg_for_update, :modify_arg_for_reply],
    :exec   =>  lambda do |cmd, arg|
                if( arg =~ /(http[s]?:\/\/._) / )
                    url = $1
                    client = Googl.client('email@account','password')
                    arg.gsub(/(http[s]?:\/\/._) /,client.shorten(url).short_url+' ')
                else
                    arg
                end
            end
)
# googl.rb

This code only manage one url per update or modify ! I'll update the code as soon as possible. You need to install googl gem.
Regards

**Comment by koichiro** [comment]
Thanks.
https://github.com/jugyo/termtter/commit/0d413dfd95162672e18fde6ef4fe920a7f2daa3d

**Comment by itwars** [comment]
Hi koichiro,

You're well come, I really enjoyed termtter ! It became my only Twitter client ;)
