### ISSUE TITLE
Direct Messages no longer work due to change in Twitter OAuth permission levels

### ISSUE THREAD

**Issue by profmaad** [jugyo/termtter#138]
Direct Messages can no longer be accessed using termtter because Twitter introduced a new permission level in its OAuth system "Read, Write & Direct Messages", everything lower no longer has access to DMs.

Please change termtters registration with the Twitter API to ask for that permission level.

More information on the change is available here: https://dev.twitter.com/docs/application-permission-model

**Comment by koichiro** [comment]
I added re-authorization mechanism in oauth.
https://github.com/jugyo/termtter/commit/96ad26bb2ddff3b9144d1fbfd821a9e078def645

@jugyo released Termtter 1.10.0 with this feature.
Please use it.

**Comment by profmaad** [comment]
Were was it released? Is it going to be uploaded to rubygems?

**Comment by jugyo** [comment]
Sorry, I failed to release.
Now, the new gem has been released.
Please try it.

**Comment by profmaad** [comment]
Works like a charm, thank you very much.
