### ISSUE TITLE
githubのissuesに投稿するプラグインを書く

### ISSUE THREAD

**Issue by Sixeight** [jugyo/termtter#24]
see also: http://twitter.com/jugyo/status/1754244892

**Comment by jugyo** [comment]
!

**Comment by Sixeight** [comment]
半分冗談で書いたのですが普通に実現できそうで困ってますw
http://develop.github.com/p/issues.html

**Comment by jugyo** [comment]
w
Search Issues もできるとすばらしいっすねー

**Comment by Sixeight** [comment]
とりあえずTyphoeusの実験もかねて書いてみました
pluginに落とし込めば完成ですね！

http://github.com/Sixeight/giic/tree/master

**Comment by Sixeight** [comment]
Giicよりコメントテスト

**Comment by Sixeight** [comment]
きた！

**Comment by jugyo** [comment]
すばらしい！

**Comment by Sixeight** [comment]
icommentも追加!
