### ISSUE TITLE
confirmation の仕組みを考える

### ISSUE THREAD

**Issue by jugyo** [jugyo/termtter#26]
confirm プラグインがあるけど、限界があると思ったので。

```
config.confirm = true
```

とかしておくと有効になるみたいな。

確認用のメッセージを簡単に出せるメソッドを Termtter::Client とかに用意して、
各コマンドで config.confirm の値を見て確認メッセージを出すかどうか決めるイメージ。

**Comment by Sixeight** [comment]
catch internal sever error (closed by 07aeed570810f611702a2817b83cc9f2b19ccbea)
