### ISSUE TITLE
retweetプラグインの補完が効かない

### ISSUE THREAD

**Issue by koichiro** [jugyo/termtter#52]
ユーザー名の補完が効いてないみたい。エラーが出ます。

<pre>
> rt @[ERROR] NoMethodError: undefined method `find_user_candidates' for Termtter::Client:Module
[ERROR] ./lib/plugins/retweet.rb:39
./lib/termtter/command.rb:43:in `call'
./lib/termtter/command.rb:43:in `complement'
./lib/termtter/client.rb:264:in `setup_readline'
/usr/lib/ruby/1.8/erb.rb:753:in `map'
./lib/termtter/client.rb:264:in `each'
./lib/termtter/client.rb:264:in `map'
./lib/termtter/client.rb:264:in `setup_readline'
./lib/termtter/client.rb:297:in `call'
./lib/termtter/client.rb:297:in `readline'
./lib/termtter/client.rb:297:in `start_input_thread'
./lib/termtter/client.rb:296:in `initialize'
./lib/termtter/client.rb:296:in `new'
./lib/termtter/client.rb:296:in `start_input_thread'
./lib/termtter/client.rb:381:in `run'
./run_termtter.rb:14
</pre>

**Comment by jugyo** [comment]
対応しましたー
