### ISSUE TITLE
Make username the standard parameter for profile 

### ISSUE THREAD

**Issue by bascht** [jugyo/termtter#90]
Hey. Most of the commands in termtter have a default parameter, like 'l' - for my personal timeline.
Would be cool if the command 'profile' would just output my personal profile.
In the moment it'll just throw an "[ERROR] JSON::ParserError: source '<html><body>You are ' not in JSON!"-error.
thats all. :-)
 Bascht

**Comment by jugyo** [comment]
I made it. Check it out. :)
718fdc7ce3edfb7ac541ed6ae0c91ad1cd82f0bb

**Comment by bascht** [comment]
Awesome! Works for me.
Thanks a lot for the quick reaction! :-)
