### ISSUE TITLE
searchコマンドで日本語検索したい

### ISSUE THREAD

**Issue by takkaw** [jugyo/termtter#96]
searchコマンドで日本語検索できると嬉しいです。
例えば、searchコマンドを以下のようにしておいて...

lang = config.search_lang.empty? ? {} : {:lang => config.search_lang}
statuses = Termtter::API.twitter.search(arg,lang)

configファイルに、config.search_lang = 'ja' と書いておくと、
日本語検索できるというのはいかがでしょうか?
configファイルにsearch_lang設定が無い場合は従来通りの動作となります。

**Comment by jugyo** [comment]
いいですねー。
というか、もう検索オプションをハッシュで指定できるようにしてしまったほうがいいかなと思いました。

   config.search.option = {:lang => 'ja'}

みたいなイメージです。

**Comment by takkaw** [comment]
なるほどー。
こちらの方が自由が効くので良いと思いました。

**Comment by jugyo** [comment]
ユーザーが lang というパラメータを知っている必要があって若干敷居が高い気がしますが、自由度が高いのでとりあえずこれで実装しようと思いますー。
日本語検索便利そうですね！

**Comment by jugyo** [comment]
実装したのでクローズ
