### ISSUE TITLE
コマンドを実行したあとに入力欄にそのコマンドまで復活する

### ISSUE THREAD

**Issue by Sixeight** [jugyo/termtter#97]
コマンドライン復活のタイミングを変更したことによって発生していると思われる

> > list
> 
> [ずらずら]
> 
> > list >

**Comment by jugyo** [comment]
5ec8f3afd6c99aad68a9ed94c219ac15830c8221 の影響だと思います。
revert しますか。

**Comment by jugyo** [comment]
revert しました 03ddd18ceea283a4b46abaf9fe2953de31b2d044

**Comment by Sixeight** [comment]
既に把握されていたのですね。
コミットに対するコメント読んでませんでした。

これはストリームしたときに入力中の物が復活しない為の変更ですが、
普通のときに問題があるので一旦もどしても良いかもしれませんね。

**Comment by jugyo** [comment]
必要な箇所で Readline.refresh_line を直接呼ぶしかないかなーと思ってます。

**Comment by mattn** [comment]
rubyでの実装は調べてないので分かりませんが、Cでよく似た挙動の実装をしたことがあります。

http://github.com/mattn/glookoo/blob/master/glookoo.cxx

メッセージ表示後に displayMessage がそれです。入力位置を保存し、最初の位置に戻し、メッセージを表示した後に入力位置を復元、行をリフレッシュという流れです。

**Comment by jugyo** [comment]
Readline.refresh_line は必要なところで個別に呼ぶようにする、ということでこの件クローズします。
print メソッドを書き換えて、mattn さんに提案していただいたやりかたでうまいことやりたい感じではあります。
