### ISSUE TITLE
日本語が入力できない

### ISSUE THREAD

**Issue by ujihisa** [jugyo/termtter#98]
Snow Leopard, Terminal.appでとくになにも設定していない状態で、ターミナル上ではことえりで日本語が入力できるのに、termtter上では日本語が入力できない。日本語を入力するとその文字が消えてビープする。

OSX付属のrubyとgemでインストールしたtermtter。

**Comment by jugyo** [comment]
そんな問題が。。
Snow Leopard いれたら確認してみます。

**Comment by BanzaiMan** [comment]
これは例のlibedit問題だと思うんですけど。違いますかね？

**Comment by jugyo** [comment]
あ、その可能性が高いですね。

**Comment by ujihisa** [comment]
// 例のlibedit問題?

http://dl.dropbox.com/u/326852/iShowU-Capture.mov
こんなかんじらしいです

**Comment by jugyo** [comment]
libedit な気がします。

**Comment by ujihisa** [comment]
libedit!

**Comment by ujihisa** [comment]
tenderlove「いや、libreadlineです」
