### ISSUE TITLE
Uncaught Zib::BufError in 'history' plugin crashes termtter

### ISSUE THREAD

**Issue by BanzaiMan** [jugyo/termtter#99]
If reading ~/.termtter/history fails (because it's corrupt, or it is empty), history plugin crashes termtter.

A simple-minded fix is here: http://gist.github.com/230550

**Comment by jugyo** [comment]
もしよければコミットしてくださいー

**Comment by BanzaiMan** [comment]
http://github.com/jugyo/termtter/commit/97236edb8b527ce16e5f02cc854089c26784287d
